#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

xset r rate 200 50 &			# speed xrate up
pacwall &		# generate the wallpaper background
#picom &    # compositor for tearing
xrdb -load ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources 	# Uncomment to use Xresources colors/settings on startup
remaps &		# run the remaps script, switching caps/esc and more; check it for more info

autostart="mpd dunst unclutter pipewire"

for program in $autostart; do
	pidof -s "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
